### ISSUE TITLE
very less throughput 

### ISSUE THREAD

**Issue by kartiksura** [mpapierski/asio_http#3]
The throughput of the example is very less.
with libpion-net i am getting 75000 qps and with this server i am getting 3482 qps
would be glad to provide more info if needed.

**Comment by mpapierski** [comment]
Sorry for late response. Please consider using https://github.com/mpapierski/http-server instead. It has better HTTP support and has clean API.

**Comment by kartiksura** [comment]
Thanks for the reply. I was exploring ASIO as a platform for a high throughput server. It seems you decided to move over to C. 
I would be highly interested to know your painpoints in ASIO.
